# paths to genome files.
# Human genome and hops genome are not included in this repository
# Download them and replace the respective lines in genomes.tsv
genomes: genomes.tsv

# change this to a path to point local, fast memory wiuth lots of free space
# for example an ssd
tmp_path: tmp
# path to the evaluation software
bpht_eval_path: bpht_eval



params:
  H:
    - 8
    - 16
  q:
    - 13
    - 15

fill_rate:
  p:
    - 22
    - 24
    - 26
  H:
    - 8
    - 10
    - 12
    - 14
    - 16
  runs:
    2
  steps:
    10

genomes_fill_time:
  q:
    - 11
    - 15
  H:
    - 8
  hfs:
    - mult
    - tab_twisted
  runs:
    2

genomes_access_time:
  q:
    - 11
    - 15
  H:
    - 8
  hfs:
    - mult
    - tab_twisted
  runs:
    2


comparison:
  H:
    - 8
    - 12
    - 16
    - 20
    - 24
  p:
    - 26
    - 22
  runs:
    2

  
new_comparison:
  H:
    - 8
    - 12
    - 16
    - 20
    - 24
  p:
    - 26
    - 22
  runs:
    2
